export const PRODUCT_LIST_REQ = 'PRODUCT_LIST_REQ';
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS';
export const PRODUCT_LIST_FALIURE = 'PRODUCT_LIST_FALIURE';

export const PRODUCT_DETAILS_REQ = 'PRODUCT_DETAILS_REQ';
export const PRODUCT_DETAILS_SUCCESS = 'PRODUCT_DETAILS_SUCCESS';
export const PRODUCT_DETAILS_FALIURE = 'PRODUCT_DETAILS_FALIURE';

export const PRODUCT_DELETE_REQ = 'PRODUCT_DELETE_REQ';
export const PRODUCT_DELETE_SUCCESS = 'PRODUCT_DELETE_SUCCESS';
export const PRODUCT_DELETE_FALIURE = 'PRODUCT_DELETE_FALIURE';

export const PRODUCT_CREATE_REQ = 'PRODUCT_CREATE_REQ';
export const PRODUCT_CREATE_SUCCESS = 'PRODUCT_CREATE_SUCCESS';
export const PRODUCT_CREATE_FALIURE = 'PRODUCT_CREATE_FALIURE';
export const PRODUCT_CREATE_RESET = 'PRODUCT_CREATE_RESET';

export const PRODUCT_UPDATE_REQ = 'PRODUCT_UPDATE_REQ';
export const PRODUCT_UPDATE_SUCCESS = 'PRODUCT_UPDATE_SUCCESS';
export const PRODUCT_UPDATE_FALIURE = 'PRODUCT_UPDATE_FALIURE';
export const PRODUCT_UPDATE_RESET = 'PRODUCT_UPDATE_RESET';
