export const PRODUCT_LIST_REQ = 'PRODUCT_LIST_REQ';
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS';
export const PRODUCT_LIST_FALIURE = 'PRODUCT_LIST_FALIURE';

export const PRODUCT_DETAILS_REQ = 'PRODUCT_DETAILS_REQ';
export const PRODUCT_DETAILS_SUCCESS = 'PRODUCT_DETAILS_SUCCESS';
export const PRODUCT_DETAILS_FALIURE = 'PRODUCT_DETAILS_FALIURE';
