export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FALIURE = 'USER_LOGIN_FALIURE';

export const USER_LOGOUT = 'USER_LOGOUT';

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FALIURE = 'USER_REGISTER_FALIURE';

export const GET_USER_DETAILS_REQUEST = 'GET_USER_DETAILS';
export const GET_USER_DETAILS_SUCCESS = 'GET_USER_DETAILS_SUCCESS';
export const GET_USER_DETAILS_FALIURE = 'GET_USER_DETAILS_FALIURE';

export const USER_DETAILS_RESET = 'USER_DETAILS_RESET';

export const UPDATE_USER_DETAILS_REQUEST = 'UPDATE_USER_DETAILS';
export const UPDATE_USER_DETAILS_SUCCESS = 'UPDATE_USER_DETAILS_SUCCESS';
export const UPDATE_USER_DETAILS_FALIURE = 'UPDATE_USER_DETAILS_FALIURE';
export const UPDATE_USER_DETAILS_RESET = 'UPDATE_USER_DETAILS_RESET';

export const USER_ORDERS_COLLECTION_REQUEST = 'USER_ORDERS_COLLECTION_REQUEST';
export const USER_ORDERS_COLLECTION_SUCCESS = 'USER_ORDERS_COLLECTION_SUCCESS';
export const USER_ORDERS_COLLECTION_FALIURE = 'USER_ORDERS_COLLECTION_FALIURE';
export const USER_ORDERS_COLLECTION_RESET = 'USER_ORDERS_COLLECTION_RESET';

export const USERS_LIST_REQUEST = 'USERS_LIST_REQUEST';
export const USERS_LIST_SUCCESS = 'USERS_LIST_SUCCESS';
export const USERS_LIST_FALIURE = 'USERS_LIST_FALIURE';
export const USERS_LIST_RESET = 'USERS_LIST_RESET';

export const USER_DELETE_REQUEST = 'USER_DELETE_REQUEST';
export const USER_DELETE_SUCCESS = 'USER_DELETE_SUCCESS';
export const USER_DELETE_FALIURE = 'USER_DELETE_FALIURE';
